FROM python:3.10-alpine

WORKDIR /usr/app/src

# updating a ton of stuff so mariadb can be installed
run apk update
run apk add gcc
run apk add mariadb-dev
run apk add musl-dev

expose 8080

copy pyproject.toml ./

copy sql_app/* ./sql_app/

RUN pip install --upgrade pip

run pip install .

CMD ["run_app"]
